from __future__ import annotations

import argparse
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


def generate_checkerboard(
    output: Path,
    inner_corners: tuple[int, int] = (9, 6),
    square_size_mm: float = 5.0,
) -> Path:
    if square_size_mm <= 0:
        raise ValueError("square_size_mm must be positive")
    columns = inner_corners[0] + 1
    rows = inner_corners[1] + 1
    board_width = columns * square_size_mm * mm
    board_height = rows * square_size_mm * mm
    page_width, page_height = A4
    origin_x = (page_width - board_width) / 2.0
    origin_y = (page_height - board_height) / 2.0 + 35 * mm

    output.parent.mkdir(parents=True, exist_ok=True)
    document = canvas.Canvas(str(output), pagesize=A4, pageCompression=1)
    document.setTitle("9x6 inner-corner 5 mm calibration checkerboard")
    document.setFont("Helvetica-Bold", 16)
    document.drawCentredString(page_width / 2, page_height - 28 * mm, "Camera Calibration Checkerboard")
    document.setFont("Helvetica", 10)
    document.drawCentredString(
        page_width / 2,
        page_height - 36 * mm,
        f"{inner_corners[0]} x {inner_corners[1]} inner corners - {square_size_mm:g} mm squares",
    )

    document.setFillColorRGB(1, 1, 1)
    document.rect(origin_x - 10 * mm, origin_y - 10 * mm, board_width + 20 * mm, board_height + 20 * mm, fill=1, stroke=0)
    document.setFillColorRGB(0, 0, 0)
    for row in range(rows):
        for column in range(columns):
            if (row + column) % 2 == 0:
                document.rect(
                    origin_x + column * square_size_mm * mm,
                    origin_y + (rows - row - 1) * square_size_mm * mm,
                    square_size_mm * mm,
                    square_size_mm * mm,
                    fill=1,
                    stroke=0,
                )

    reference_y = origin_y - 30 * mm
    document.setLineWidth(0.4)
    document.line(origin_x, reference_y, origin_x + board_width, reference_y)
    for index in range(columns + 1):
        x = origin_x + index * square_size_mm * mm
        tick = 3 * mm if index in (0, columns) else 1.5 * mm
        document.line(x, reference_y - tick, x, reference_y + tick)
    document.setFont("Helvetica", 9)
    document.drawCentredString(
        origin_x + board_width / 2,
        reference_y - 7 * mm,
        f"Reference length: {columns * square_size_mm:g} mm",
    )

    instructions = [
        "Print at Actual Size / 100 percent. Disable Fit to Page.",
        "Mount the paper flat on a rigid board. Avoid folds, bubbles, blur, and glare.",
        "Measure several adjacent squares with a caliper and record the average pitch.",
    ]
    text = document.beginText(25 * mm, 32 * mm)
    text.setFont("Helvetica", 9)
    text.setLeading(13)
    for line in instructions:
        text.textLine(line)
    document.drawText(text)
    document.setFont("Helvetica", 8)
    document.drawRightString(page_width - 20 * mm, 15 * mm, "Generated by Machine-Vision-Project")
    document.showPage()
    document.save()
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a printable calibration checkerboard PDF")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("output/pdf/checkerboard-9x6-5mm.pdf"),
    )
    parser.add_argument("--square-mm", type=float, default=5.0)
    parser.add_argument("--corners-x", type=int, default=9)
    parser.add_argument("--corners-y", type=int, default=6)
    args = parser.parse_args(argv)
    output = generate_checkerboard(
        args.output,
        inner_corners=(args.corners_x, args.corners_y),
        square_size_mm=args.square_mm,
    )
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
